 # Use the latest version of the official .NET SDK image
FROM mcr.microsoft.com/dotnet/aspnet:8.0


# Set the working directory
WORKDIR /workspace

# (Optional) Add any additional setup or tools required

# Expose ports if needed
EXPOSE 80

# (Optional) Set any environment variables if needed

# Set default command to start a shell
CMD ["bash"]
